<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="6" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-28T19:15:11 GST" name="Suite" finished-at="2024-08-28T19:15:55 GST" duration-ms="44341">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorMessageValidationsTest.loginErrorValidation()[pri:0, instance:com.scompany.Tests.ErrorMessageValidationsTest@66ea810]" name="loginErrorValidation" class="com.scompany.Tests.ErrorMessageValidationsTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:com.scompany.Tests.SubmitOrderTest@7a5ceedd]" name="submitOrder" class="com.scompany.Tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2024-08-28T19:15:11 GST" name="Error Message Validations Test" finished-at="2024-08-28T19:15:43 GST" duration-ms="32305">
      <class name="com.scompany.Tests.ErrorMessageValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.scompany.Tests.ErrorMessageValidationsTest@66ea810]" started-at="2024-08-28T19:15:11 GST" name="launchApplication" finished-at="2024-08-28T19:15:16 GST" duration-ms="5563" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginErrorValidation()[pri:0, instance:com.scompany.Tests.ErrorMessageValidationsTest@66ea810]" started-at="2024-08-28T19:15:16 GST" name="loginErrorValidation" finished-at="2024-08-28T19:15:17 GST" duration-ms="517" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email  password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email  password.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.scompany.Tests.ErrorMessageValidationsTest.loginErrorValidation(ErrorMessageValidationsTest.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:com.scompany.Tests.ErrorMessageValidationsTest@66ea810]" started-at="2024-08-28T19:15:17 GST" name="closeApplication" finished-at="2024-08-28T19:15:17 GST" duration-ms="195" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.scompany.Tests.ErrorMessageValidationsTest@66ea810]" started-at="2024-08-28T19:15:17 GST" name="launchApplication" finished-at="2024-08-28T19:15:22 GST" duration-ms="4887" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:com.scompany.Tests.ErrorMessageValidationsTest@66ea810]" started-at="2024-08-28T19:15:22 GST" name="loginErrorValidation" finished-at="2024-08-28T19:15:23 GST" duration-ms="1067" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email  password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email  password.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.scompany.Tests.ErrorMessageValidationsTest.loginErrorValidation(ErrorMessageValidationsTest.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:com.scompany.Tests.ErrorMessageValidationsTest@66ea810]" started-at="2024-08-28T19:15:23 GST" name="closeApplication" finished-at="2024-08-28T19:15:24 GST" duration-ms="137" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.scompany.Tests.ErrorMessageValidationsTest@66ea810]" started-at="2024-08-28T19:15:24 GST" name="launchApplication" finished-at="2024-08-28T19:15:28 GST" duration-ms="4611" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productErrorValidation()[pri:0, instance:com.scompany.Tests.ErrorMessageValidationsTest@66ea810]" started-at="2024-08-28T19:15:28 GST" name="productErrorValidation" finished-at="2024-08-28T19:15:43 GST" duration-ms="14655" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:com.scompany.Tests.ErrorMessageValidationsTest@66ea810]" started-at="2024-08-28T19:15:43 GST" name="closeApplication" finished-at="2024-08-28T19:15:43 GST" duration-ms="233" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- com.scompany.Tests.ErrorMessageValidationsTest -->
    </test> <!-- Error Message Validations Test -->
    <test started-at="2024-08-28T19:15:11 GST" name="Submit Order Test" finished-at="2024-08-28T19:15:55 GST" duration-ms="44341">
      <class name="com.scompany.Tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.scompany.Tests.SubmitOrderTest@7a5ceedd]" started-at="2024-08-28T19:15:11 GST" name="launchApplication" finished-at="2024-08-28T19:15:16 GST" duration-ms="5206" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:com.scompany.Tests.SubmitOrderTest@7a5ceedd]" started-at="2024-08-28T19:15:16 GST" name="submitOrder" data-provider="getData" finished-at="2024-08-28T19:15:32 GST" duration-ms="15529" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sheza@123, itemName=ZARA COAT 3, email=saj@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:com.scompany.Tests.SubmitOrderTest@7a5ceedd]" started-at="2024-08-28T19:15:32 GST" name="closeApplication" finished-at="2024-08-28T19:15:32 GST" duration-ms="218" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.scompany.Tests.SubmitOrderTest@7a5ceedd]" started-at="2024-08-28T19:15:32 GST" name="launchApplication" finished-at="2024-08-28T19:15:35 GST" duration-ms="3436" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:com.scompany.Tests.SubmitOrderTest@7a5ceedd]" started-at="2024-08-28T19:15:35 GST" name="submitOrder" data-provider="getData" finished-at="2024-08-28T19:15:51 GST" duration-ms="15213" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Iamking@000, itemName=ADIDAS ORIGINAL, email=anshika@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:com.scompany.Tests.SubmitOrderTest@7a5ceedd]" started-at="2024-08-28T19:15:51 GST" name="closeApplication" finished-at="2024-08-28T19:15:51 GST" duration-ms="254" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.scompany.Tests.SubmitOrderTest@7a5ceedd]" started-at="2024-08-28T19:15:51 GST" name="launchApplication" finished-at="2024-08-28T19:15:54 GST" duration-ms="3477" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="orderHistory()[pri:0, instance:com.scompany.Tests.SubmitOrderTest@7a5ceedd]" started-at="2024-08-28T19:15:54 GST" name="orderHistory" finished-at="2024-08-28T19:15:55 GST" depends-on-methods="com.scompany.Tests.SubmitOrderTest.submitOrder" duration-ms="682" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistory -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:com.scompany.Tests.SubmitOrderTest@7a5ceedd]" started-at="2024-08-28T19:15:55 GST" name="closeApplication" finished-at="2024-08-28T19:15:55 GST" duration-ms="139" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- com.scompany.Tests.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
  </suite> <!-- Suite -->
</testng-results>
